name: "Chromatic Deployment"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: 3a57ca82faac
          token: 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
